### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by niklas88** [fmi-alg/OsmGraphCreator#1]
I'm having trouble compiling this. First there should be "git submodule init" in the Readme. Second I'm getting the following error:

   -- Configuring done
   CMake Error at vendor/sserialize/CMakeLists.txt:173 (add_library):  
     Cannot find source file:

```
   vendor/libs/geographiclib/legacy/C/geodesic.c

 Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
 .hxx .in .txx
  CMake Error: Cannot determine link language for target "sserialize".
  CMake Error: CMake can not determine linker language for target: sserialize
```

**Comment by dbahrdt** [comment]
Hi,
The problem is that you also have to initialize the submodules of the submodules (and so on). Consider cloning the repository with --recursive which does all submodule cloning for you. I've updated the readme accordingly
